name: kepi
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.50846
title: Kepi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-69059829-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#acbba5'
    - '#588594'
    - '#2b0e29'
    - '#e9da30'
    - '#cf7639'
  brandStrength: 0.5
  lightness: null
  saturation: null
  rhythmicContrast: null
purpose: []
